services:
#host 52.231.108.82
  mysqldb:
    image: dinhphu/bookshop-backend-mysql:1.1.2
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    # network_mode: host
    networks:
      snowplow:
        ipv4_address: 172.19.0.2
    volumes:
      - ./data/mysql:/var/lib/mysql

  bookshop-backend:
    image: dinhphu/bookshop-backend:1.1.1
    container_name: bookshop-backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.19.0.2:3306/customer-data-platform
      - BACKEND_HOST=52.231.108.82
    depends_on:
      - mysqldb
    ports:
      - 10000:10000
    # network_mode: host
    networks:
      snowplow:
        ipv4_address: 172.19.0.3
    volumes:
      - ./data/backend/images:/book-shop-web/backend/public/static/images

  postgresdb:
    image: dinhphu/iglu-postgres:1.0.0
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql
    # network_mode: host
    networks:
      snowplow:
        ipv4_address: 172.19.0.4

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper:/var/lib/zookeeper
    # network_mode: host
    networks:
      snowplow:
        ipv4_address: 172.19.0.5

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
#    volumes:
#      - ./data/kafka1:/var/lib/kafka/data
    networks:
      snowplow:
        ipv4_address: 172.19.0.6
    # network_mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 52.231.108.82:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://52.231.108.82:9092,PLAINTEXT_HOST://52.231.108.82:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  elasticsearch2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
#    container_name: elasticsearch2
#    hostname: elasticsearch2
#    restart: always
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - "node.name=elasticsearch2"
#      - "bootstrap.memory_lock=true"
#      - "cluster.name=es-cluster"
#      - "discovery.seed_hosts=20.214.141.95"
#      - "network.publish_host=52.231.108.82"
#      - "cluster.initial_master_nodes=20.214.141.95,52.231.108.82"
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#      - "xpack.security.enabled=false"
#      - "xpack.security.http.ssl.enabled=false"
#      - "xpack.security.transport.ssl.enabled=false"
#    networks:
#      snowplow:
#        ipv4_address: 172.19.0.7
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9200"]
#      interval: 30s
#      timeout: 10s
#      retries: 30
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    deploy:
#      resources:
#        limits:
#          memory: 3g

  iglu-server:
    image: dinhphu/snowplow-iglu:1.0.0
    container_name: iglu-server
    # restart: always
    ports:
      - 8181:8181
    depends_on:
      - postgresdb
    # network_mode: host
    networks:
      snowplow:
        ipv4_address: 172.19.0.10

  collector:
    image: dinhphu/snowplow-collector:1.0.2
    container_name: collector
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kafka1
    # network_mode: host
    networks:
      snowplow:
        ipv4_address: 172.19.0.11

  enrich:
    image: dinhphu/snowplow-enrich:1.0.2
    container_name: enrich
    restart: always
    depends_on:
      - kafka1
      - iglu-server
    # network_mode: host
    networks:
      snowplow:
        ipv4_address: 172.19.0.12

  # loader:
  #   image: dinhphu/snowplow-loader:1.1.2
  #   container_name: loader
  #   # restart: always
  #   environment:
  #     - BOOTSTRAP_SERVERS=20.214.141.95:9092,52.231.108.82:9092
  #     - ES_HOSTS=20.214.141.95:9200,52.231.108.82:9200
  #     - MYSQL_HOST=52.231.108.82
  #   depends_on:
  #     - enrich
  #     - kafka1
  #   # network_mode: host
  #   networks:
  #     snowplow:
  #       ipv4_address: 172.19.0.13

networks:
  snowplow:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
